%YAML 1.2
---

name: continuous-deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Build docs
        run: |
          cd packages/docs
          yarn build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          # cname: da-michele.com
          commit_message: 'deploy:'
